### ISSUE TITLE
Determine if we can use rekognition

### ISSUE THREAD

**Issue by netskink** [rtp-aws/devpost_aws_disaster_response#1]
From watching the class nothing in particular jumps out as usable for this project.  The markdown notes are here.  Possibly we could demo something.  If someone doesn't feel like doing the real stuff, they could play with that. It won't hurt it the work can be used in the future for something else.

**Comment by adrianxdev** [comment]
recognition gives this: Railway
93.7 %
Rail
93.7 %
Train Track
93.7 %
Transportation
93.7 %
Bridge
86.5 %
Building
86.5 %
Road
68.9 %

**Comment by adrianxdev** [comment]
When not snow covered, the results are very different: Results
Road
99.9 %
Highway
99 %
Freeway
99 %
Bridge
56.3 %
Building
56.3 %

**Comment by adrianxdev** [comment]
So, a little hacky but yes, if rekognition thinks its a road, its not an icy bridge. If rekognition thinks its a railway, its a snowy / icy road...not necessarily detecting the ice as you want but instead keying off the travel tracks in the lanes of the cars / trucks on the snow.

**Comment by adrianxdev** [comment]
This is where I tested it. and I cropped out any text or other info from the image so that only the road was in view. There is one cam that overlays DOT info on teh image. That will be hard to use. We'll want a clear view of the road and no other info on the image (for example, cropping in 5/10% of the image from the top and botton. Here is a link to the interactive rekognition tool: https://us-west-2.console.aws.amazon.com/rekognition/home?region=us-west-2#/label-detection

**Comment by netskink** [comment]
This online interactive tool is awesome.  Many thanks.  I wonder if it detects daytime or nighttime.  That is the next pruning thing to do really.

**Comment by netskink** [comment]
Hmm. it has custom labels. It also has "lighting" on the one which I uploaded with a streetlight on.
I should have save the url name for the file. I just clicked around in my file folder until I found one in the dark
![Screenshot from 2022-01-16 13-22-43](https://user-images.githubusercontent.com/4422172/149672793-94e0b27f-da96-492c-a078-591d8e17973e.png)
.

**Comment by netskink** [comment]
The more i look at this, it is appealing to me.  I'll try to get the forked cloudacadmey sample working so that I can get cognitio and S3 working with a deployed model.

**Comment by netskink** [comment]
Got the rek code working for S3/local image via cli and also vis webapp.  Ive long decided to use rek.  This issue can be closed.
