### ISSUE TITLE
Find some other good cameras

### ISSUE THREAD

**Issue by netskink** [rtp-aws/devpost_aws_disaster_response#5]
Look in the mountains to west.  find ones which are high res and have good detail like this

**Comment by netskink** [comment]
continue to add cameras. Probably should start removing some cameras.

**Comment by zacharyjones123** [comment]
windy.com is an api that popped up that may be worth looking into. The website is really cool also. windy.com

https://api.windy.com/webcams

**Comment by netskink** [comment]
@zacharyjones123 Interesting.

**Comment by netskink** [comment]
I added a test setup at home with my own camera to keep a fixed perspective.  I've also briefly looked into some orthorectification algorithms.  I hope to avoid this, but if necessary I will create a specific issue in future.  For now, I've added enough ncdot cameras.  I've also identified on the web app which cameras are preferred due to high resolution.
