### ISSUE TITLE
All these bridges look kind of bad when dusk arrives

### ISSUE THREAD

**Issue by netskink** [rtp-aws/devpost_aws_disaster_response#7]
No need to pull images overnight.  The bad ones will need to cut.  

Two things come to mind

* modify the crontab to stop at dusk and resume at dawn.  The drawback is we miss the one the camera which is well lit.
* modify the webscrape script. create two sets of scripts.  one that runs 24h and the one which runs dusk to dawn. see above.

**Comment by adrianxdev** [comment]
Looks like you have the timestamp in the filename. What is the format? We can drop / ignore the images outside of the desired time frame during training. Keep it grabbing as is.

**Comment by netskink** [comment]
The cron script pulls dawn to dusk.  In process of getting ground truth and rekognition to build first level classifier of images to determine if the camera is showing a valid image capable of prediction.
